version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-server
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    networks:
      - html_network

  php:
    image: php:8.3-fpm
    container_name: php-nginx-app
    volumes:
      - ./html:/var/www/html
    networks:
      - html_network

networks:
  html_network:
    driver: bridge
